spring:
  profiles:
    active: local
    include:
      - core
      - batch
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    database: h2
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
search:
  kakao:
    URL: https://dapi.kakao.com/v2/search/blog
    REST_API_KEY: 168f49791c65ed92825014082de464c4